// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://naswgeeruzxbhmjiskqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hc3dnZWVydXp4Ymhtamlza3FjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NjMyOTMsImV4cCI6MjA1ODAzOTI5M30.f37oKYgmzLIIXImCrXMpkXQO6E9JlHQAzWB68ibfNOU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);